add waitForDeploy and progress args
kolonialno/velo-action pull request #24
Opened 2021-08-04 11:26 UTC by andersliland

2021-08-04 14:15 UTC, trondhindenes requested changes
a wrong description, and a suggestion to making booleans a bit more robust by parsing them "properly"

2021-08-04 14:15 UTC, trondhindenes commented on velo_action/action.py
> +    args.progress = True if args.progress == "True" else False
its good to accept case-insensitive true/false, so if you do 
`args.progress = True if args.progress.lower() == "true" else False` you allow "true" or "True" or "TRUE".

An even better approach is to use the `strtobool` function:
```
from distutils.util import strtobool

>>> strtobool('True')
1
>>> strtobool('False')
0
```
This will support "yes/no", "1/0" and all kinds of things.

2021-08-04 14:15 UTC, trondhindenes commented on action.yml
> +      Show progress of the deployment.
this description is probably not correct.

2021-08-05 05:43 UTC, andersliland commented on action.yml
> +      Show progress of the deployment.
true, thanks

2021-08-05 05:43 UTC, andersliland commented on velo_action/action.py
> +    args.progress = True if args.progress == "True" else False
nice will test

2021-08-05 07:23 UTC, trondhindenes requested changes

2021-08-05 07:23 UTC, trondhindenes commented on velo_action/action.py
> +    args.create_release = strtobool(args.create_release)
you have to cast as bool. Remember to test stuff!!!

```
In [2]: strtobool('1')
Out[2]: 1

In [3]: bool(strtobool('1'))
Out[3]: True

In [4]: bool(strtobool('0'))
Out[4]: False

In [5]: bool(strtobool('yes'))
Out[5]: True

In [6]: bool(strtobool('no'))
Out[6]: False

In [7]: bool(strtobool('true'))
Out[7]: True

In [8]: bool(strtobool('True'))
Out[8]: True

In [9]: bool(strtobool('no'))
Out[9]: False
```

2021-08-05 13:21 UTC, trondhindenes commented
wow this took a while. I didn't understand where the "None" stuff comes from, but its defined in actions.yml so that makes sense. I've changed the codebase to be more pythonic by setting the `None` strings to "actually None"; which makes it easier to check on them. Booleans are also converted to actual bools using the `strtobool` function.

Added a bunch of tests for parsing the args.

Theres a lot more that could be done with the codebase in order to make it nicer, probably using pydantic's `BaseSettings` (which auto-parses envvars) instead of going thru an arg-parser is better and would make the code a lot cleaner.

In any case, it should be in good enough shape to merge now.

2021-08-05 13:39 UTC, trondhindenes commented
just for later ref: 
If action.yml contains an input with a default, GH Actions will pass an empty string (`"") in the environment variable. This is actually perfect, but doesn't work well with the current argparser. So the whole input/arg logic should probably be rewritten.

2021-08-06 13:38 UTC, trondhindenes approved these changes

2021-08-09 07:13 UTC, andersliland commented
Really nice! Approved! (cannot approve since i opened the pr)

When using a local .env file with custom values the tests fail. Could we prevent the tests from using .env file?

2021-08-09 08:11 UTC, trondhindenes commented
> When using a local .env file with custom values the tests fail. Could we prevent the tests from using .env file?

Understood. I guess that happens because the tests expect stuff to be "unfilled" except the mocked envvars. I can fix that.

2021-08-09 09:39 UTC, andersliland commented
Tests are successful now!
We should test this in example-repo before making a new release.

2021-08-09 10:00 UTC, trondhindenes commented
> Tests are successful now!
> We should test this in example-repo before making a new release.

Testing it here: https://github.com/kolonialno/example-deploy-project/pull/11/checks - merging if/when that pipelines succeed.

2021-08-09 10:07 UTC, trondhindenes commented
example-deploy-project looks good, so merging this.

2021-08-09 10:08 UTC, merged