Remove semver generation, use git rev as default
kolonialno/velo-action pull request #59
Opened 2021-12-08 20:29 UTC by RmMsr

SemVer versions are not needed. So we can remove the GitVersion dependency. The default version is now a shortened got rev (hash).

2021-12-13 12:16 UTC, andersliland requested changes

2021-12-13 12:16 UTC, andersliland commented on .github/workflows/test.yaml.disable
> -        with:
this is still required for `git rev-parse --short HEAD` as the command gives different length hash depending on the uniqueness
https://stackoverflow.com/questions/44286795/why-does-git-rev-parse-short-use-a-non-default-length#:~:text=When%20running%20git%20rev%2Dparse,hash%20output%20of%20length%209.

2021-12-13 12:16 UTC, andersliland commented on action.yml
> +      Version used to generate release and tag image. Defaults to the shortened git hash.
add comment here with the command that is used and a warning that `git rev-parse --short HEAD` may give different results in a shallow clone of the repo compared to a full one.

2021-12-13 12:16 UTC, andersliland commented on action.yml
> +  image: docker://europe-docker.pkg.dev/nube-artifacts-prod/nube-container-images-public/velo-action:814516a
That artifact registry is deprecated
use this 

```suggestion
  image: docker://europe-docker.pkg.dev/nube-hub/docker/velo-action:814516a
```

2021-12-13 12:16 UTC, andersliland commented on changelog.md
> +  [this example](https://github.com/kolonialno/velo/blob/c3d5ddff650fd97357b72ef178d93e5519eb5efa/.github/workflows/ci.yml#L71-L114)
add comment about sha length, see my comment above

2021-12-13 12:16 UTC, andersliland commented on docs/release.md
> +   We are using [GCP artifacts](https://console.cloud.google.com/artifacts/docker/nube-artifacts-prod/europe/nube-container-images-public?project=nube-artifacts-prod).
```suggestion
   We are using [GCP artifacts](https://console.cloud.google.com/artifacts/browse/nube-hub?project=nube-hub).
```

2021-12-13 12:16 UTC, andersliland commented on docs/release.md
> +     image: docker://europe-docker.pkg.dev/nube-artifacts-prod/nube-container-images-public/velo-action:1234567
```suggestion
     image: docker://europe-docker.pkg.dev/nube-hub/docker/velo-action:1234567
```

2021-12-13 13:45 UTC, RmMsr commented on .github/workflows/test.yaml.disable
> -        with:
Oh, I did not know. Thanks.

I was removing the full depth ti hopefully get the code a bit faster.

2021-12-14 11:27 UTC, RmMsr commented on action.yml
> +      Version used to generate release and tag image. Defaults to the shortened git hash.
Good point.

2021-12-14 11:27 UTC, RmMsr commented on action.yml
> +  image: docker://europe-docker.pkg.dev/nube-artifacts-prod/nube-container-images-public/velo-action:814516a
Oh, I thought it is the other way around. Where is the source of truth on that?

2021-12-14 11:54 UTC, RmMsr commented on changelog.md
> +  [this example](https://github.com/kolonialno/velo/blob/c3d5ddff650fd97357b72ef178d93e5519eb5efa/.github/workflows/ci.yml#L71-L114)
Done

2021-12-22 08:21 UTC, andersliland approved these changes

2021-12-22 08:21 UTC, andersliland commented on action.yml
> +      Version used to generate release and tag image. Defaults to the shortened git hash.
```suggestion
      Version used to generate release and tag image. Defaults to the shortened git hash (`git rev-parse --short HEAD`) .
            NOTE: The length of the Git hash is dynamic. It can be longer if it is not unique.
```

2021-12-22 08:21 UTC, andersliland commented on docs/release.md
> +The version of the action is determined by the release tag. It is used when
```suggestion
The version of the action is determined by the Github release tag. It is used when
```

2021-12-22 17:10 UTC, merged