Octopus API
kolonialno/velo-action pull request #72
Opened 2022-01-03 13:36 UTC by RmMsr

https://github.com/kolonialno/velo/issues/154

2022-01-03 15:19 UTC, larseen commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
This is quite wierd? 
Why are we looking up stuff as a secret using GCP?
Is this becasue it is a action and we dont want do require skjer a?crets to be avialable? 
Seems strange that we can not give it settings/configuration from environment

2022-01-03 21:14 UTC, RmMsr commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
Good question. I am not sure why exactly. I see two benefits. It's working the same with minimal configuration from any platform (local, kubernetes, Github). And the configuration is centrally managed and versioned. I don't feel much motivation to change it.

2022-01-04 10:03 UTC, andersliland commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
The idea is to reduce the inputs to velo-action as much as possible to make it easy to use. 

By only suppling the Google Service Account Key, the action can fetch the rest from Secret Manager.

The alternative is that every velo-action instance in Github Action Workflow must add the Octopus server and API key as secrets from Github...

2022-01-04 10:20 UTC, andersliland requested changes
Would love some tests on the Octopus class.

And an update to the docs on how to run the action locally when developing.

How can this easily be tested agains example deploy project for instance?

2022-01-04 10:20 UTC, andersliland commented on velo_action/action.py
> -            raise ValueError("gcp service account key not specified")
Why change this? It the Service Account is not specified the action should stop and return an exception

2022-01-04 10:20 UTC, andersliland commented on velo_action/gcp.py
> +            logger.info("Using local credentials")
What if no service account key is specified and local credentials dont exist?

We should return a nice error for the Github workflow log...

2022-01-04 10:20 UTC, andersliland commented on velo_action/octopus_api.py
> +    def _determine_latest_deploy_packages(self, project_id):
does this allow us to select the velo version to use when creating a release?

2022-01-04 10:20 UTC, andersliland commented on velo_action/octopus_api.py
> +class Octopus:
would love some tests on this class!

2022-01-04 10:38 UTC, RmMsr commented on velo_action/octopus_api.py
> +class Octopus:
Indeed. We have to figure out what to test. I think the data model between server and client do not provide much value to test. I ll look through the functions and see if there is some logic that I can easily test

2022-01-04 10:41 UTC, RmMsr commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
By the way. the velo-action can now be ran with your local gcloud credentials. You just need to grant yourself the privileges to access the secrets.

2022-01-04 10:43 UTC, RmMsr commented on velo_action/action.py
> -            raise ValueError("gcp service account key not specified")
Yes, as the primary use case is still within GitHub workflows. I thought that qualifies for a warning.

2022-01-04 10:44 UTC, RmMsr commented on velo_action/gcp.py
> +            logger.info("Using local credentials")
Yes, we can. The 403 you get from the gcp SDK is not so bad though.

2022-01-04 10:46 UTC, RmMsr commented on velo_action/gcp.py
> +            logger.info("Using local credentials")
That is:

```google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

But we should add a note for `INPUT_SERVICE_ACCOUNT_KEY`

2022-01-04 16:38 UTC, larseen commented on velo_action/octopus_api.py
> +class Octopus:
this is easily done by mocking the api functions and ensuring the called variable matching what is expected, any more than this is not needed

2022-01-04 20:06 UTC, RmMsr commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
What authentication would that be? The velo-action in any case needs to interact with gcp.

2022-01-05 09:23 UTC, RmMsr commented on velo_action/gcp.py
> +            logger.info("Using local credentials")
Added a better error message.

For missing credentials: 

> RuntimeError: No valid credentials to access Google cloud. Please either specify the INPUT_SERVICE_ACCOUNT_KEY environment or authenticate using 'gcloud auth login'.


For lack of permissions:

> RuntimeError: Missing permission to access secret 'velo_action_octopus_server' in project 'nube-velo-prod'. Elevate your permissions with: klipy power elevate --group nube.project.editor.nube-velo-prod

2022-01-06 08:46 UTC, andersliland commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
https://cloud.google.com/iam/docs/workload-identity-federation

and

https://github.com/marketplace/actions/authenticate-to-google-cloud#authenticating-via-workload-identity-federation

but this requires us to setup the identity-federation first

2022-01-11 09:03 UTC, RmMsr commented on velo_action/action.py
>          octopus_cli_server = g.lookup_data(
Ok, thanks.

2022-01-28 08:19 UTC, larseen commented on velo_action/action.py
> +        commit_id = proc_utils.execute_process(
Use the `GITHUB_SHA` env variable and just make it shorter
https://docs.github.com/en/actions/learn-github-actions/environment-variables

2022-01-31 13:54 UTC, andersliland commented
resolves https://github.com/kolonialno/cloud-platform-tasks/issues/301

2022-01-31 15:38 UTC, andersliland approved these changes
Made some lint and refactor changes.

Removed the process_utils as this was not used. Made an explicit function for generating version.

2022-02-01 06:52 UTC, RmMsr commented on velo_action/settings.py
> -# type: ignore
Ahh, that's why the properties did not show up in the linter. I overlooked that.

2022-02-01 10:13 UTC, merged