Feat/velo version
kolonialno/velo-action pull request #89
Opened 2022-02-08 10:10 UTC by larseen

# This adds support for selecting velo version

if no version is specified it will select the latest, if a version is specified it will select the best matching.

```
version: 0.2 => selects the highest patch
version: 0 => selects the highest minor and highest patch
```

2022-02-09 08:49 UTC, andersliland requested changes
Also make a PR updating the action docs in the velo repo https://github.com/kolonialno/velo/blob/main/docs/action.md

- removing the project input
- document version  semver selection.

Also add a version field in https://github.com/kolonialno/velo/blob/main/docs/app-spec.md

2022-02-09 08:49 UTC, andersliland commented on velo_action/main.py
> +            velo_project = velo_config.get("project", None)
you should add some error if the project or version is not found.

Not many services have set the project in app.yaml. This update would force them to do this (which is good) but they need to get a warning to help them along the way

2022-02-09 09:43 UTC, larseen commented on velo_action/main.py
> +            velo_project = velo_config.get("project", None)
If the version is not found it will select the latest based on the previous mechanism, but yeah project might be nice to fail on 🆗

2022-02-09 11:48 UTC, andersliland approved these changes

2022-02-15 07:00 UTC, RmMsr commented on action.yml
> +    required: false
Let's add a deprecation warning that people will note that this setting is without effect. So they can migrate over to use the app.yaml.

2022-02-15 07:00 UTC, RmMsr commented on velo_action/main.py
> +            velo_project = velo_config.get("project", None)
Maybe we should make it more obvious that the version affect's only velo. I think just having a `version` in the app.yaml could be confusing especially as we already have a variable `version` there.

2022-02-15 08:57 UTC, RmMsr approved these changes
Nice implementation. As stated before I think we should make it easier for the user to understand how and where to set project name and velo version. Otherwise ready to go.

2022-02-15 08:57 UTC, RmMsr commented on velo_action/utils.py
> +) -> Optional[str]:
Nice. I should use the Optional[] return type more often.

2022-02-15 13:40 UTC, andersliland commented on action.yml
> +    required: false
agree.
```suggestion
    required: false
```

2022-03-10 12:17 UTC, RmMsr approved these changes
Should be good to go. I found nothing blocking. 

I am not yet sure what the users should actually put in the velo version and how they integrate updating the velo dependency into their daily work. But that maybe does no need to be answered here.

Still, I think the re-use of `version` in velo needs to be changed: https://github.com/kolonialno/velo/blame/main/docs/app-spec.md#L14-L29 (see earlier comment in this PR)

2022-03-22 13:51 UTC, andersliland commented on action.yml
> +    required: false
removed project as input

2022-04-11 13:12 UTC, andersliland commented on velo_action/octopus/release.py
> +    def create(  # pylint: disable=inconsistent-return-statements
yes

2022-04-12 15:15 UTC, closed without merging

2022-04-12 15:41 UTC, andersliland commented
moved here https://github.com/kolonialno/velo-action/pull/114